### ISSUE TITLE
Добавить что-то в SimpleAdmin

### ISSUE THREAD

**Issue by purpl3-yt** [purpl3-yt/SimpleModules#1]

**Comment by purpl3-yt** [comment]
мне лень, изя не релизает са
@izzy8799

**Comment by izzy8799** [comment]
Та бож, патерпі немнога...

**Comment by purpl3-yt** [comment]
> Та бож, патерпі немнога...

ладно, подожду

**Comment by dest4590** [comment]
> Та бож, патерпі немнога...

кагда..

@izzy8799

**Comment by dest4590** [comment]
> Та бож, патерпі немнога...

@izzy8799 
када...
